version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pg_data

  app:
    build: .
    ports:
      - '8000:8000'
    depends_on:
      - db

