# Generated by Django 5.0.1 on 2024-03-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0007_car_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='moto',
            name='amount',
            field=models.IntegerField(default=1000, verbose_name='Цена'),
        ),
    ]
